events {}

http {
    upstream billing_backend {
        # O Docker Compose resolve "billing_api" para os 3 containers em round-robin
        server billing_api:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://billing_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
