services:
  bot_student:
    build: .
    environment:
      - BOT_TYPE=student
      - TARGET_URL=https://10.10.100.4
    networks:
      - lab_bridge

  bot_professor:
    build: .
    environment:
      - BOT_TYPE=professor
      - TARGET_URL=https://10.10.100.4
    networks:
      - lab_bridge

  bot_ddos:
    build: .
    environment:
      - BOT_TYPE=ddos
      - TARGET_URL=https://10.10.100.4
    networks:
      - lab_bridge

networks:
  lab_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
