services:
  bot_student:
    build: .
    environment:
      - BOT_TYPE=student
      - TARGET_URL=${TARGET_URL:-https://10.10.100.4}
      - DB_HOST=${DB_HOST:-10.10.100.4}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-intranet_user}
      - DB_PASS=${DB_PASS:-bcd127}
      - DB_NAME=${DB_NAME:-intranet_db}
    networks:
      - lab_bridge

  bot_professor:
    build: .
    environment:
      - BOT_TYPE=professor
      - TARGET_URL=${TARGET_URL:-https://10.10.100.4}
      - DB_HOST=${DB_HOST:-10.10.100.4}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-intranet_user}
      - DB_PASS=${DB_PASS:-bcd127}
      - DB_NAME=${DB_NAME:-intranet_db}
    networks:
      - lab_bridge

  bot_ddos:
    build: .
    environment:
      - BOT_TYPE=ddos
      - TARGET_URL=${TARGET_URL:-https://10.10.100.4}
    networks:
      - lab_bridge

  bot_soa:
    build: .
    environment:
      - BOT_TYPE=soa_stress
      - TARGET_URL=${TARGET_URL:-https://10.10.100.4}
    networks:
      - lab_bridge

networks:
  lab_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.100.0/24
