version: '3.8'
services:
  traffic_bot:
    build: .
    container_name: web_traffic_bot
    environment:
      # Mude essas variáveis para corresponder à sua VM Ubuntu alvo
      - TARGET_IP=192.168.1.50
      - TARGET_USER=ubuntu
      - TARGET_PASS=sua_senha_aqui
    restart: unless-stopped
    # Permite acesso à rede do host para facilitar o roteamento SSH até a VM Ubuntu no GNS3
    network_mode: "host"