services:
  snmpsim:
    image: tandrup/snmpsim
    container_name: snmpsim_pi
    ports:
      - "10161:161/udp"
    volumes:
      - ./data:/usr/snmpsim/data
    restart: unless-stopped
    networks:
      - sim_snmp_net
    command: >
      --agent-udpv4-endpoint=0.0.0.0:161
      --process-user=snmpsim
      --process-group=snmpsim
      --data-dir=/usr/snmpsim/data

networks:
  sim_snmp_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.101.0/24
