services:
  snmpsim:
    image: tandrup/snmpsim
    container_name: snmpsim_pi
    ports:
      - "10161:161/udp"
    volumes:
      - ./data:/usr/snmpsim/data
    restart: unless-stopped
    networks:
      - sim_snmp_net
    command:
      - "snmpsimd.py"
      - "--agent-udpv4-endpoint=0.0.0.0:161"
      - "--process-user=snmpsim"
      - "--process-group=nogroup"
      - "--data-dir=/usr/snmpsim/data"

  bruteforce:
    build: ../bruteforce_simulator
    container_name: bruteforce_pi
    networks:
      - sim_snmp_net
    volumes:
      # Mantemos apenas o volume compartilhado para o Python escrever o arquivo
      - ./data:/data
    environment:
      - SNMPREC_PATH=/data/security_monitor.snmprec
      - TARGET_URL=https://10.10.100.4/login
      - CONCURRENCY=10
    # RESTAURADO: Mantém o container vivo e ocioso aguardando o gatilho da sua página web
    command: ["tail", "-f", "/dev/null"]
    restart: unless-stopped

  traffic_bot:
    build: ../web_traffic_simulator
    container_name: web_traffic_bot
    restart: unless-stopped
    # Permite acesso à rede do host para facilitar o roteamento SSH até a VM Ubuntu no GNS3
    network_mode: "host"
    command: ["tail", "-f", "/dev/null"]

  soa_stress_bot:
    image: alpine:latest
    container_name: soa_stress_pi
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ../web_panel/scripts:/scripts
    # Instala o Apache Bench (ab) silenciosamente no boot e fica ocioso aguardando comandos
    command: ["sh", "-c", "apk add --no-cache apache2-utils && tail -f /dev/null"]

networks:
  sim_snmp_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.101.0/24